sudo: required
dist: xenial

language: go
go_import_path: github.com/hyperhq/hyperd

go:
  - 1.8

env:
  - HYPER_EXEC_DRIVER=qemu    HYPER_STORAGE_DRIVER=aufs
#  - HYPER_EXEC_DRIVER=qemu    HYPER_STORAGE_DRIVER=rawblock
#  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=overlay
#  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=rawblock
#  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=btrfs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev libvirt-bin aufs-tools wget libaio1 libpixman-1-0 netcat realpath libelf-dev
  - wget https://s3-us-west-1.amazonaws.com/hypercontainer-download/qemu-hyper/qemu-hyper_2.4.1-1_amd64.deb && sudo dpkg -i --force-all qemu-hyper_2.4.1-1_amd64.deb
  - cd `mktemp -d`
  - mkdir -p ${GOPATH}/src/github.com/hyperhq
  - wget http://mirrors.kernel.org/sourceware/lvm2/LVM2.2.02.131.tgz
  - tar xf LVM2.2.02.131.tgz
  - cd LVM2.2.02.131
  - ./configure > /dev/null && make device-mapper > /dev/null && sudo make install > /dev/null

# override the default `install`, otherwise default `install` will export ${TRAVIS_BUILD_DIR}/Godeps/_workspace as GOPATH
# see https://docs.travis-ci.com/user/languages/go#Dependency-Management

install:
  - cd ${TRAVIS_BUILD_DIR}
  - hack/install-grpc.sh
  - hack/verify-gofmt.sh
  - hack/verify-generated-proto.sh
  - sed -i 's/\(^.*defaultCPUModel.*=\)\(.*$\)/\1 \"core2duo\"/' vendor/github.com/kata-containers/runtime/virtcontainers/qemu_arch_base.go
  - sed -i 's/accel=kvm/accel=tcg/' vendor/github.com/kata-containers/runtime/virtcontainers/qemu_amd64.go
  - ./autogen.sh && ./configure && make

script:
  - ./scripts/kata-env-setup.sh
  - cd ${TRAVIS_BUILD_DIR} && hack/test-cmd.sh
